services:
  agr_ai_adapter:
    image: ghcr.io/${org}/agr-ai-adapter:${AGR_AI_ADAPTER_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    restart: always
    platform: linux/amd64
    depends_on:
      - agr_ai_tools
      - agr_intent_classifier
    environment:
      DETECT_LANGUAGE_API: ${DETECT_LANGUAGE_API}
      TRANSLATE_LANGUAGE_API: ${TRANSLATE_LANGUAGE_API}
      INTENT_CLASSIFIER_API: ${INTENT_CLASSIFIER_API}
      GENERAL_TASK_API: ${GENERAL_TASK_API}
      MODEL_NAME: ${MODEL_NAME}
      WEAVIATE_HTTP: ${WEAVIATE_HTTP}
      WEAVIATE_URL: ${WEAVIATE_URL}
      MISTRAL_URL: ${MISTRAL_URL}
