services:
  agr_controller:
    image: ghcr.io/${org}/agr-controller:${DEMO_SERVICE_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    restart: always
    platform: linux/amd64
    depends_on:
      - ai_adaptor
    environment:
      DATABASE_URL: ${DATABASE_URL}
      # Indian bank
      INDIAN_BANK_URL: ${INDIAN_BANK_URL}
      INDIAN_BANK_CLIENT_ID: ${INDIAN_BANK_CLIENT_ID}
      INDIAN_BANK_CLIENT_SECRET: ${INDIAN_BANK_CLIENT_SECRET}
      INDIAN_BANK_CHANNEL: ${INDIAN_BANK_CHANNEL}
      INDIAN_BANK_CHANNEL_VALUE: ${INDIAN_BANK_CHANNEL_VALUE}
      INDIAN_BANK_CLIENT_CERTIFICATE: ${INDIAN_BANK_CLIENT_CERTIFICATE}
      INDIAN_BANK_BRANCH_NUMBER: ${INDIAN_BANK_BRANCH_NUMBER}
      INDIAN_BANK_TELLER_NUMBER: ${INDIAN_BANK_TELLER_NUMBER}
      INDIAN_BANK_TERMINAL_NUMBER: ${INDIAN_BANK_TERMINAL_NUMBER}
      BASEURL: ${BASEURL}
      MISTRAL_BASE_URL: ${GENERAL_TASK_API}